### ISSUE TITLE
Add the ability to hide the close button

### ISSUE THREAD

**Issue by fabiomanz** [niklashenning/pyqt-toast#4]
I am unsure what the cleanest way to accomplish this is, but I would like to have the ability to show no close button on the toast. I currently do it with a transparent image, but it would be cool if we could do it directly with no hacks. 

Maybe we could add a method to set the hide flag of this button.

Where do you think would be the best point to add this functionality?

**Comment by niklashenning** [comment]
Thanks for opening this issue!

This is actually something I wanted to add in the next release along with some other minor features. In the meantime, you can achieve this by setting the close button size to 0 like so: `toast.setCloseButtonSize(QSize(0, 0))`
This way, you don't have to add a transparent icon and the button won't still be clickable.

I'll implement this by adding an attribute like `close_button_enabled` and adjusting the `__setup_ui` method so the button will be hidden when it's set to False, which shouldn't take long.

Also thanks for submitting a pull request. I'll take a look at it (most likely over the weekend) and if everything looks good, I can release a new updated version in a couple of days
